import { GetStaticProps } from "next";
import Head from "next/head";
import { ICard } from "../component/Card";
import Nav from "../component/Nav";
import type { Place } from "../component/NavPlaces/NavPlaces";
import ShowCase from "../component/Showcase";
import styles from "./mobile.module.css";

type params = { data: ICard[], places: Place[] };
export default function Home({ data, places }: params) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <Nav.Mobile places={places} />
        <ShowCase.Mobile data={data} />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<params> = (context) => {
  return {
    props: {
      data: [
        {
          imageSrc: "/samples/camisa.jpg",
          price: 15000,
          quotas: 6,
          title: "Camisa Top",
        },
        {
          imageSrc: "/samples/camisa.jpg",
          price: 15000,
          quotas: 6,
          title: "Camisa Top",
        },
        {
          imageSrc: "/samples/camisa.jpg",
          price: 15000,
          quotas: 6,
          title: "Camisa Top",
        },
        {
          imageSrc: "/samples/camisa.jpg",
          price: 15000,
          quotas: 6,
          title: "Camisa Top",
        },
      ],
      places: [["COLECCIÓN SS'23", "#"], ["LÍNEAS", "#"], ["REBAJAS", "#"], ["CONTACTO", "#"]]
    }, // will be passed to the page component as props
  };
};
